# Site settings
title: METRO | 599
email: info@metro.org
description: Where New York's libraries and archives come together to learn, share ideas, and collaborate.

footer:
  address:
    - line: Metropolitan New York Library Council
    - line: 599 11th Avenue, 8th floor
    - line: New York, NY 10036
  phone: 212.228.2320
  fax: 212.228.2598

twitter:
  username: mnylc

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
- title: twitter
  url: http://twitter.com/mnylc
  img: /assets/img/logos/Twitter_Logo_White_On_Blue.png
- title: facebook
  url: https://www.facebook.com/METROlibrarycouncil/
  img: /assets/img/logos/FB-f-Logo__blue_50.png
- title: MailChimp
  url: http://eepurl.com/b-Oik9
  img: /assets/img/logos/mc_script_white.png

# Content settings
defaults:
  -
    scope:
      type: "posts"
      path: "_posts/jobs"
    values:
      permalink: "/jobs/:title"
      tags:
        - job
  -
    scope:
      type: "posts"
      path: "_posts/news"
    values:
      permalink: "/news/:title"
      tags:
        - news
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"

# Build settings
markdown: kramdown

# Attribution
attribution:
  image:
    source: Thomas Hawk
    url: https://flic.kr/p/eSTiRb
  theme:
    source: Rick Kim
    name: agency
    url: https://github.com/y7kim/agency-jekyll-theme

gems:
  - jekyll-seo-tag
